steps:
  - label: "CUDA Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.9"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="CUDA")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("FastIce")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3

  - label: "AMDGPU Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.9"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="AMDGPU")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("FastIce")'
    agents:
      queue: "juliagpu"
      rocm: "*"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3
    env:
      JULIA_NUM_THREADS: 4
env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  env:
    SECRET_SECRET_CODECOV_TOKEN: "tFZu0T9JDLkDnbB6Y+7MbESLm6EORnsfb0N52QldNHj/GgtVzP0Z8u/PhEjNPE6x7BieL05ekgxpEay+oIMYMd7gPHKV/ZDTvml8HcWzyIzoebX2n/31K51A4d5z7scrX3ieBuYGfT3HNdQFQUpsYrILKhXr6su4/jhuEFnNNHdPsoUInrAytJRV7jrYVWm4En/bmDOoQFcC4XfpXQ5FNeUjsj6WRDRgfYuWvGaxlVLEtIM3bvjnZzBbVhNn0a1zq108Dx9eWL237j6iEhuCrXTbNJ9V1AHEQsN4gKNIJQE7l+loA3ks6GDPatnULGZfGonxa9nAbgAU6l/eL+ni0w==;U2FsdGVkX1/NqS5QMOmbPQ2VnMcPoLARLhkarEhtjGRCktadVVX1C+3MyyWOiocIA0VDIcOlMt3U8WZSTBpp9Q=="