steps:
  - label: "CUDA Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.9"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="CUDA")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("FastIce")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3

  - label: "AMDGPU Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.9"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.version}}"
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e 'println("--- :julia: Instantiating project")
                using Pkg
                Pkg.develop(; path=pwd())
                Pkg.develop(; name="AMDGPU")' || exit 3

      julia -e 'println("+++ :julia: Running tests")
                using Pkg
                Pkg.test("FastIce")'
    agents:
      queue: "juliagpu"
      rocm: "*"
    timeout_in_minutes: 120
    soft_fail:
      - exit_status: 3
    env:
      JULIA_NUM_THREADS: 4
env:
  SECRET_CODECOV_TOKEN: "DzfWQ/PaiozJqs8Qa6Fr/FXksQl/XmLSfFnsTdwPlEyb53N6vqTC3BEK3UUuHzhxQ09Vk2k5aLFhMPQj0rjEaxhWs9F8yIrKm7oA2wrfBF6zrekYFx6TEvCgjmkDOKWdkoA7l3dehdpWBFik8gwewv5aoEWw9UU676oKHLIm4Uo6c+UiBewUsgFRMgIaZcOdRfYLnlOvJgSLPTvP5ZQgl3oadj4MkuxZ6Fnga+WMsgxjRFbwa+lzHxtDU18Uu2Dt37hIkYg2ao00qrg4yO2LlMRiMJ5Ep6D8BNT9Gv2IZsgE1RbtUhnPNOcWyPpE9gyZ4US1+DQedFfrd6WmypyKXg==;U2FsdGVkX19b2qK57Ep2zHChVU9VifiaBCwObMydUrsOhvwUxpFAl46v2lTX6X0p5ta9uDltDklUUf2bhtptWA=="