- group: "CUDA"
  key: "cuda"
  steps:
   - label: "Tests -- Julia latest"
     plugins:
       - JuliaCI/julia#v1:
           version: "1"
           persist_depot_dirs: packages, artifacts, compiled
     agents:
       queue: "juliagpu"
       cuda: "11.0"
     if: build.message !~ /\[skip tests\]/
     timeout_in_minutes: 60
     env:
       JULIA_CUDA_MEMORY_POOL: "none"
     commands: |
       echo "+++ Run tests"
       julia --color=yes --project=. -e '
          import Pkg
          Pkg.test("FastIce")
          '
- group: "ROCm"
  key: "rocm"
  steps:
   - label: "Tests -- Julia latest"
     plugins:
       - JuliaCI/julia#v1:
           version: "1"
           persist_depot_dirs: packages, artifacts, compiled
     agents:
       queue: "juliagpu"
       rocm: "*" # todo fix ROCM version
     if: build.message !~ /\[skip tests\]/
     timeout_in_minutes: 60
     soft_fail:
       - exit_status: 1
     commands: |
       echo "+++ Run tests"
       julia --color=yes --project=. -e '
          import Pkg
          Pkg.test("FastIce")
          '