# see: https://github.com/staticfloat/forerunner-buildkite-plugin
steps:
  - label: "CUDA Julia {{matrix.version}}"
    matrix:
      setup:
        version:
          - "1.9"
    plugins:
      - staticfloat/forerunner:
          watch:
            - ".buildkite/**"
            - "src/**"
            - "ext/**"
            - "test/**"
          target: .buildkite/run_tests.yml
    agents:
      queue: "juliagpu"
