# see: https://github.com/staticfloat/forerunner-buildkite-plugin
steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner:
          watch:
            - ".buildkite/**"
            - "src/**"
            - "ext/**"
            - "test/**"
          target: .buildkite/run_tests.yml
    agents:
      queue: "juliagpu"
