# see: https://github.com/staticfloat/forerunner-buildkite-plugin
steps:
  - label: ":runner: Dynamically launch Pipelines"
    plugins:
      - staticfloat/forerunner:
          watch:
            - ".buildkite/**/*.yml"
            - "**/*.toml"
            - "src/**/*.jl"
            - "ext/**/*.jl"
            - "test/**/*.jl"
          target: .buildkite/run_tests.yml
    agents:
      queue: "juliagpu"
